### ISSUE TITLE
[BUG] Scale Slider doesn't have direct numerical entry

### ISSUE THREAD

**Issue by VexWerewolf** [Kuenaimaku/Hex-Size-Support#11]
You have to drag the scale slider by hand, and given that I almost always want tokens to be 1.25 or 1.5 scale, having to get this perfect every single time is kind of a drag.

**Comment by Kuenaimaku** [comment]
This is not a bug - Foundry's range input has a span that shows the current value next to it. There's no good way to specifically change this span to an input field without it effecting all range inputs.
