### ISSUE TITLE
Feature Request: Snap to Vertex default setting in module settings

### ISSUE THREAD

**Issue by sealtrowitz** [Kuenaimaku/Hex-Size-Support#5]
A feature request myself and my playgroup would love to see would be for the Snap to Vertex setting to be able to be unchecked as default. We never play with it ourselves, and we often forget to turn it off for every new size 2/4 token until it's actually time to play. Ideally, adding a setting within module settings that could be checked to set all new size 2/4 tokens with Snap to Vertex disabled by default, that would allow people who like/use that setting to keep it on by default, while allowing others who don't to turn it off by default.

**Comment by Kuenaimaku** [comment]
With the move to v10 and some of the under the hood changes, this is only an issue in v9 as "alternative snapping" and "snap to vertex" are now obsolete. I can try to backport this to v9 in a custom release that can be manually installed.
