### ISSUE TITLE
[BUG] Drag Ruler forces Alternative Snap regardless of orientation

### ISSUE THREAD

**Issue by msprijatelj** [Kuenaimaku/Hex-Size-Support#6]
This may be more of a Drag Ruler issue, but I figured I'd bring it up here: When using Drag Ruler v1.13.2 with HTSS v2.0.1, Drag Ruler forces Size 2/4 tokens to use the vertex defined by "Alternative Orientation" (aka the default Foundry Size 2/4 orientation) instead of dynamically swapping vertices with the orientation. This leads to weird line-ups of Size 2/4 tokens on a hex grid.

Screenshots of the issue:
![image](https://user-images.githubusercontent.com/44978587/210706359-360803aa-d645-4e9a-ae26-ab57c4feac47.png)
![image](https://user-images.githubusercontent.com/44978587/210706397-8857b5a0-fb17-4de0-a5a7-c52e3bd480a4.png)

Systems info:
Windows 10
Lancer v1.4.0-beta.1
Foundry v10.291
Foundry App

**Comment by Kuenaimaku** [comment]
I've tried replicating this with Lancer v1.4.2 within Foundry v10.291 and the Foundry App and haven't been able to replicate this. Do you have pathfinding enabled? Here's what I have enabled.

![](https://i.imgur.com/FWaQ9JH.png)

**Comment by Kuenaimaku** [comment]
> I've tried replicating this with Lancer v1.4.2 within Foundry v10.291 and the Foundry App and haven't been able to replicate this. Do you have pathfinding enabled? Here's what I have enabled.

nevermind - able to replicate now! 😓

**Comment by Z3nner** [comment]
I'm also having this issue.  You can see when using WASD to move around, the token aligns correctly with the grid in either orientation.  But when dragging and dropping the orientation for the preview and the alignment of the token does not flip.

[htss201.webm](https://user-images.githubusercontent.com/76132631/213898459-09cb74b2-b1d1-4c05-8ce3-d9abd5e448da.webm)

**Comment by msprijatelj** [comment]
Heh, now **I'm** having trouble replicating this on the following:

- Foundry v10
- Lancer v1.4.2
- Drag Ruler v1.13.2
- HTSS v2.0.2

Not sure if this is due to a Drag Ruler update, HTSS update, or Lancer update (kicking myself for not checking my versions for all of these when I created the ticket). If you can't reproduce this anymore, feel free to close the ticket.

**Comment by Kuenaimaku** [comment]
closing until reproducible again (if ever).
